repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: 03770b120e9a4dddcaf3662059ac0948e97c1825
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-vet-mod
      - id: go-mod-tidy
