SERVICE:
  NAME: notion-boy
  HOST: "0.0.0.0"
  PORT: 8001
  URL: http://localhost:8001

WECHAT:
  APP_ID:
  APP_SECRET:
  TOKEN:
  ENCODING_AES_KEY:

DATABASES:
  SQLITE:
    FILE: data.db
  MYSQL:
    HOST:
    PORT:
    USER:
    PASS:
    DATABASE:

NOTION_OAUTH:
  CLIENT_ID:
  CLIENT_SECRET:
  REDIRECT_URI:
  AUTH_URL: https://api.notion.com/v1/oauth/authorize?owner=user
  TOKEN_URL: https://api.notion.com/v1/oauth/token
