
name: Go

on:
  push:
  pull_request:

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install go imports
      run: go install golang.org/x/tools/cmd/goimports@latest
    - uses: pre-commit/action@v2.0.3

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make build

    - name: Test
      run: go test -v ./...
